"""boolean column added to project, so that each project can specify whether a their project allows weights to be given for each bill

Revision ID: 025e924d1fe5
Revises: 8ecc442cd1db
Create Date: 2020-02-22 21:13:28.219125

"""

# revision identifiers, used by Alembic.
revision = '025e924d1fe5'
down_revision = '8ecc442cd1db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('advanced_weighting_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'advanced_weighting_enabled')
    # ### end Alembic commands ###
