"""added weight to billowers table & created BillOwers association object

Revision ID: 8ecc442cd1db
Revises: 6c6fb2b7f229
Create Date: 2020-02-22 16:53:40.074814

"""

# revision identifiers, used by Alembic.
revision = '8ecc442cd1db'
down_revision = '6c6fb2b7f229'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billowers', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billowers', 'weight')
    # ### end Alembic commands ###
